# Kitty Configuration - AikoHyprSetup

# Font
font_family      JetBrainsMono Nerd Font
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size 12.0

# Window
remember_window_size  no
initial_width  950
initial_height 500
window_padding_width 15
confirm_os_window_close 0

# Background & Transparency
background #1E2023
background_opacity 0.95
dynamic_background_opacity yes

# Colors (Pink Anime Palette)
foreground #ffd7e8
selection_background #ff8fbd
selection_foreground #1E2023
cursor #ff8fbd

# Tabs
active_tab_foreground   #1E2023
active_tab_background   #ff8fbd
inactive_tab_foreground #ffd7e8
inactive_tab_background #2a2d31

# Keybinds
map ctrl+shift+c copy_to_clipboard
map ctrl+shift+v paste_from_clipboard

# Mouse
hide_window_decorations yes
